# Generated by Django 4.1.13 on 2024-04-30 14:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_panier_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panier',
            old_name='user',
            new_name='username',
        ),
        migrations.AddField(
            model_name='panier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
